### ISSUE TITLE
Error when login

### ISSUE THREAD

**Issue by tzheng-splunk** [freyta/7Eleven-Python#37] opened 2019-09-08 07:33 UTC
Cannot login, get 302 error in log

172.17.0.1 - - [08/Sep/2019 07:30:44] "GET / HTTP/1.1" 200 -
172.17.0.1 - - [08/Sep/2019 07:31:01] "POST /login HTTP/1.1" 302 -
172.17.0.1 - - [08/Sep/2019 07:31:03] "GET / HTTP/1.1" 200 -

**Comment by NGPriest** [comment] 2019-09-08 07:53
302 isn't an error...
302 is a status code...

> The HTTP response status code 302 Found is a common way of performing URL redirection. The HTTP/1.0 specification (RFC 1945) initially defined this code, and gave it the description phrase "Moved Temporarily" rather than "Found".
>
> https://en.wikipedia.org/wiki/HTTP_302

**Comment by tzheng-splunk** [comment] 2019-09-10 13:44
So what is the solution?

**Comment by NGPriest** [comment] 2019-09-10 14:00
@tzheng-splunk I'm not sure, i don't even know what the problem is...

**Comment by freyta** [comment] 2019-09-10 18:20
Explain what's happening. What's the actual error message? Give us more information and we may try and help you more

**Comment by NGPriest** [comment] 2019-10-21 10:15
Should we close this issue? :S

**Closed as completed** 2019-11-09 20:21 UTC
